### ISSUE TITLE
とりあえず、書いてみた

### ISSUE THREAD

**Issue by shoyan** [balloonbros/zombie-book#1]
### 戸建ての場合

戸建てに住んでいる場合、篭城をするのが得策である。
ドアや窓に鍵をかけ、カーテンと雨戸を全て閉めなければならない。
ゾンビは光や音を察知するので、なるべく光や音を外に漏らさないことが肝心である。

篭城は2階で可能な限り長期間行う。
数ヶ月、数年になることを覚悟しておかねばならない。

長期間の篭城に備えて、家にある全ての食料を2階に運ぶ必要がある。

そして、篭城に必要な物資を運び終えたら、階段を壊す。

ゾンビが窓を破って入ってくる可能性があるので、確実に壊さねばならない。
通常のゾンビには、はしごを登ったりするほどの知能はないので、階段を壊しておけば2階の安全は確保される。
この作業を行うかどうかで、生存の確率が大きく変わってくる。

ここで大事な点は、階段を壊すときに火を使ってはならないことだ。
うまいこと階段だけ焼き払おうとしても、大抵の場合うまくいかず、家自体が全焼してしまうだろう。
### マンションの場合

うーん、どうしたらいいんだろう・・・
### 地下

地下には絶対に行ってはいけない。
階段を落ちたゾンビは下に溜まる。
ゾンビは登るのは得意ではないので、必然的に下に溜まっていく傾向にある。
よって、地下道でゾンビと遭遇する可能性はかなり高い。
### 動物園

ゾンビウィルスは動物にも感染する。
典型的なのは犬だ。
大型犬がゾンビ化すると、俊敏性の高いやっかい極まりないゾンビとなってしまう。
さらに大型の動物、例えば、ライオンや虎がゾンビ化してしまうと、もう手に負えない。
ロケットランチャーやマシンガンでもない限り撃退するのは無理だろう。
遭遇してしまった場合、ほとんど助かる見込みはない。
### 火をつける

ゾンビに火をつけてはいけない。
ゾンビは痛みを感じないので、火をつけてもしばらくは動くことができる。
ゾンビについた火で火傷をおってしまったり、物に引火して火事になる可能性がある。
火のついたゾンビが暴れると手に負えないことになってしまう。

**Comment by shoyan** [comment]
@tkengo @keitakawamoto 
とりあえず、書いてみた。まだまだ、調査不足なので、色々調査しないとなあ・・・

**Comment by keitakawamoto** [comment]
[![LGTM](http://www.lgtm.in/p/wHu3)](http://www.lgtm.in/i/wHu3)

[:+1:](http://www.lgtm.in/u/wHu3)

**Comment by keitakawamoto** [comment]
README.mdがシュールすぎてやばい
