### ISSUE TITLE
github pages作成

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/zombie-book#4]
そこからダウンロードしてもらう形式。

**Comment by keitakawamoto** [comment]
http://balloonbros.cc/zombie-book/ ページ自体を @shoyan が用意。ここに中身を用意する。
仮の中身タイポしとる...

**Comment by keitakawamoto** [comment]
### アクセス解析を設置
- BBアカウントのGoogle アナリティクス使用（これを機会にBB,IntoにもBBアカウントで設置）
- DLボタンにはクリックイベントを設置しDL数計測

**Comment by keitakawamoto** [comment]
## レイアウト・装飾進捗 70%

![image](https://cloud.githubusercontent.com/assets/1661325/10653152/c233c7c8-7897-11e5-800c-43a50d3655fe.png)

![image](https://cloud.githubusercontent.com/assets/1661325/10653162/dde19b76-7897-11e5-9af9-f8c45db749cd.png)
- 背景固定（スクロールによる変化なし）・コンテンツのみスクロール
- ゾンビシルエットは以下より入手し選択・調整（フッタにライセンス表記で使用可能・詳しく再確認）
  - http://jp.freepik.com/free-vector/zombie-silhouette-collection_797829.htm
  - http://jp.freepik.com/free-vector/undead-silhouette-collection_802533.htm
  - http://jp.freepik.com/index.php?goto=2&k=zombie&order=2&vars=2
- 背景がクオリティ低くないか？
- ダウンロードボタンのカラーは目立つが濃い青の色相が`病院的なクリーンさ`とはイメージが少し違う感じがするので調整して寄せる

**Comment by keitakawamoto** [comment]
![image](https://cloud.githubusercontent.com/assets/1661325/10657417/f635f45a-78c5-11e5-9bbb-574c8aae5be0.png)
- 現状の背景をやめた（クリーンさが低くなりすぎた）
- 背景は心電図 SVGアニメーションをアクセントとして実装
- ごちゃごちゃするので掲載例撤去
- テキストに薄いシャドウをつけてみる

**Comment by shoyan** [comment]
わくわくするなー

**Comment by keitakawamoto** [comment]
### download属性

html5のdownload属性を使うと、zipに圧縮していなくてもダウンロード形式で配布ができる。
- `PDF表示 -> ユーザーがダウンロード` とする必要はなくなる
- 反面、中身を確認できずにダウンロードすることになるが、だいたい電子書籍とはそういうものだと思うので問題はないと判断する。

http://html5.cyberlab.info/elements/text/a-download.html

**Comment by keitakawamoto** [comment]
### download属性 2

iOSではdownload要素つけてもまず展開される。

![2015-10-28 10 06 43](https://cloud.githubusercontent.com/assets/1661325/10779777/ac048b96-7d78-11e5-97d3-6a9725f99979.png)

**Comment by keitakawamoto** [comment]
一旦完成 http://balloonbros.cc/zombie-book/
