### ISSUE TITLE
各ページ作成・各種設定

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/zombie-book#5]
全ページのレイアウトについて決める

**Comment by keitakawamoto** [comment]
### サイズは~~A4~~ B5

~~いろいろな書籍を見てみたところA4で問題なさそう。~~

http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q126959957
B5にする。

※オライリー本は `B5変` の模様 http://www.oreilly.co.jp/sales/2010/04/howto-use-bookcover-2010-fair-goods.html

**Comment by keitakawamoto** [comment]
### 本文書体

http://howto.fanweb.jp/archives/51
ここが参考になる。

今のところは以下で生成。文字のサイズについては調整中。

![image](https://cloud.githubusercontent.com/assets/1661325/10775057/e5c395dc-7d48-11e5-88d5-3253038715f4.png)

**Comment by keitakawamoto** [comment]
ざっくりと流し込んでみたところ、よいページ数になりそう。
![image](https://cloud.githubusercontent.com/assets/1661325/10774948/fd8b7546-7d47-11e5-9191-cd7cd869f27a.png)

**Comment by keitakawamoto** [comment]
### リッチブラック

本文の色はおなじみの `C60 M40 Y40 K100` のリッチブラックかな。
http://www.graphic.jp/technical/check_ai/prt_black02.php

**Comment by keitakawamoto** [comment]
### 本文の段落の頭は一文字開ける

![image](https://cloud.githubusercontent.com/assets/1661325/10775512/646c0498-7d4c-11e5-9c51-71245b63b240.png)

**Comment by keitakawamoto** [comment]
### PDFテスト

いい感じ。

![image](https://cloud.githubusercontent.com/assets/1661325/10775902/eed1334e-7d4f-11e5-8724-61ce4d01f7d8.png)

**Comment by shoyan** [comment]
うおー！いい感じだ :+1:

**Comment by shoyan** [comment]
縦書きのバージョンもみてみたい。

**Comment by keitakawamoto** [comment]
@shoyan 

うーん、小説ではないから、縦書きにするのは違和感があるなあ。（馴染みがあまりないことに基づく）
医療は西洋文化の側面が大きいので、医療っぽさも軽減してしまうし。今回は横組みでいこうと思う。

![image](https://cloud.githubusercontent.com/assets/1661325/10776292/73a92cd6-7d53-11e5-8ae4-012bb5d8d9df.png)

**Comment by shoyan** [comment]
ふむふむ。横でいきますか。

**Comment by keitakawamoto** [comment]
## PDFテスト

#### 拡大・縮小、テキストの選択：OK

![2015-10-28 10 06 40](https://cloud.githubusercontent.com/assets/1661325/10779810/28601368-7d79-11e5-833d-4edd957488e5.png)
![2015-10-28 10 06 43](https://cloud.githubusercontent.com/assets/1661325/10779811/2881861a-7d79-11e5-900e-9c48b86e0cc6.png)
![2015-10-28 10 07 15](https://cloud.githubusercontent.com/assets/1661325/10779812/28981baa-7d79-11e5-8e49-c210b71b88cc.png)
![2015-10-28 10 07 35](https://cloud.githubusercontent.com/assets/1661325/10779832/7fe2d210-7d79-11e5-9614-0d2f549c6e47.png)

#### iBooksでの閲覧：OK

正しく右にページをめくってくれる。

![2015-10-28 10 10 50](https://cloud.githubusercontent.com/assets/1661325/10779823/531f5636-7d79-11e5-9247-fabec272c0ee.png)

**Comment by keitakawamoto** [comment]
### 現状ではスマホビューで読みにくい

本文横幅を広げ、以下くらいの文字の大きさに変更する。
※スマホで見るとだいぶ見やすくなっている

![img_2784](https://cloud.githubusercontent.com/assets/1661325/10779861/f083c2f4-7d79-11e5-9f2d-92a5c6d261d5.PNG)

**Comment by keitakawamoto** [comment]
## 本文テンプレート完成

テスト確認済み。これに流し込んでいく。

![image](https://cloud.githubusercontent.com/assets/1661325/10780148/ad606c8a-7d7d-11e5-9a64-0138a1b9f727.png)

**Comment by shoyan** [comment]
モバイルでも閲覧できるとは最高だ :+1:

**Comment by keitakawamoto** [comment]
### 誤字脱字
- p12 `バッド` -> `バット`

**Comment by keitakawamoto** [comment]
### 裁ち落とし（トリムマーク）は０に

![image](https://cloud.githubusercontent.com/assets/1661325/10827722/c9387984-7eb3-11e5-9422-2c02d3b9a554.png)

そうしなければ、背景色を変えた時に縁に余白が設けられ思い通りの出力ができない。

**Comment by keitakawamoto** [comment]
~~iOSでグラデーションは再現できない？そもそもグラデーションの出来もいまいちだったので単色に変更した。~~

iOSの色飛び問題はグラデーションのせいでもシャドウのせいでもなかった。
おそらくIllustratorの設定の問題だが、時間がないので解像度を合わせPhotoshop上で一枚絵にしそちらを代用した。

**Comment by keitakawamoto** [comment]
電子書籍完成 http://balloonbros.cc/zombie-book/zombie-book.pdf
